# Generated by Django 4.2.1 on 2023-06-08 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ximba', '0004_alter_profile_profile_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='city',
            field=models.CharField(default='Pretoria', max_length=50),
        ),
        migrations.AddField(
            model_name='event',
            name='suburb',
            field=models.CharField(default='Hatfield', max_length=50),
        ),
    ]
